language: rust
rust:
  - 1.12.0
  - stable
  - nightly
os:
  - linux
  - osx

# Using 16MB stacks for deep test/debug recursion
env:
  global:
    - RUST_MIN_STACK=16777216

matrix:
  include:
  - rust: nightly
    env: FEATURES=unstable
    os: linux
  - rust: nightly
    env: FEATURES=unstable
    os: osx

script:
  - cargo build --features="$FEATURES"
  - |
    if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo test --features="$FEATURES" &&
      cargo test --features="$FEATURES" -p rayon-core &&
      cargo test --features="$FEATURES" -p rayon-demo &&
      ./ci/highlander.sh
    fi
